"""
Browser Info Model - 向后兼容模块

此文件作为浏览器相关模型的统一入口点，重新导出分类后的模型。
保持向后兼容性。
"""

# 重新导出所有分类后的模型
from app.models.core.fingerprint import *
from app.models.core.browser_info import *
from app.models.core.browser_exec import *
from app.models.runtime.operations import (
    RPAClickParams,
    BrowserClickParams,
    ClickResponse,
    RPAFillParams,
    RPAScrollParams,
    RPAEvaluateParams,
    RPAScreenshotParams,
    RPAWaitParams,
    RPANavigateParams,
    JavaScriptExecuteParams,
    ExecuteJsResponse,
    SecurityCheckParams,
    SecurityRisk,
    SecurityCheckResult,
    RPAResponse,
)
from app.models.runtime.api import (
    BrowserFingerprintCreateParams,
    BrowserFingerprintUpdateParams,
    BrowserFingerprintUpsertParams,
    BrowserFingerprintQueryParams,
    BrowserFingerprintDeleteParams,
    BrowserFingerprintListParams,
    BrowserFingerprintRenameParams,
    BrowserFingerprintCreateResp,
    BrowserFingerprintUpdateResp,
    BrowserFingerprintDeleteResp,
    BrowserFingerprintRenameResp,
    BrowserFingerprintQueryResp,
    BrowserOperationOpenUrlParams,
    BrowserOperationScreenshotParams,
    BrowserOperationReleaseParams,
    BrowserOperationOpenUrlResp,
    BrowserOperationScreenshotResp,
    BrowserOperationReleaseResp,
    UserBrowserInfoCreateParams,
    UserBrowserInfoUpsertParams,
    UserBrowserInfoCreateResp,
    UserBrowserInfoCountParams,
    UserBrowserInfoListParams,
    UserBrowserInfoReadParams,
    UserBrowserInfoReadResp,
    UserBrowserInfoUpdateParams,
    UserBrowserInfoUpdateResp,
    UserBrowserInfoDeleteParams,
    UserBrowserInfoDeleteResp,
    BrowserOpenUrlParams,
    BrowserOpenUrlResp,
    BrowserScreenshotParams,
    BrowserScreenshotResp,
    BrowserReleaseParams,
    BrowserReleaseResp,
)

__all__ = [
    *[
        "PlatformEnum",
        "BrowserEnum",
        "Int32",
        "BaseFingerprintBrowserInitParams",
        "UserBrowserToken",
        "UserBrowserInfoBase",
        "UserBrowserDefaultSetting",
        "UserBrowserServerSideDefaultSetting",
        "UserBrowserInfoWithoutPlugin",
        "UserBrowserInfo",
        "UserBrowserDefaultSettingRequest",
        "UserBrowserDefaultSettingResponse",
        "BrowserExecInfoModel",
        "BrowserExecInfoModels",
    ],
    # Operations models
    "RPAClickParams",
    "BrowserClickParams",
    "ClickResponse",
    "RPAFillParams",
    "RPAScrollParams",
    "RPAEvaluateParams",
    "RPAScreenshotParams",
    "RPAWaitParams",
    "RPANavigateParams",
    "JavaScriptExecuteParams",
    "ExecuteJsResponse",
    "SecurityCheckParams",
    "SecurityRisk",
    "SecurityCheckResult",
    "RPAResponse",
    # API models
    "BrowserFingerprintCreateParams",
    "BrowserFingerprintUpdateParams",
    "BrowserFingerprintUpsertParams",
    "BrowserFingerprintQueryParams",
    "BrowserFingerprintDeleteParams",
    "BrowserFingerprintListParams",
    "BrowserFingerprintRenameParams",
    "BrowserFingerprintCreateResp",
    "BrowserFingerprintUpdateResp",
    "BrowserFingerprintDeleteResp",
    "BrowserFingerprintRenameResp",
    "BrowserFingerprintQueryResp",
    "BrowserOperationOpenUrlParams",
    "BrowserOperationScreenshotParams",
    "BrowserOperationReleaseParams",
    "BrowserOperationOpenUrlResp",
    "BrowserOperationScreenshotResp",
    "BrowserOperationReleaseResp",
    "UserBrowserInfoCreateParams",
    "UserBrowserInfoUpsertParams",
    "UserBrowserInfoCreateResp",
    "UserBrowserInfoCountParams",
    "UserBrowserInfoListParams",
    "UserBrowserInfoReadParams",
    "UserBrowserInfoReadResp",
    "UserBrowserInfoUpdateParams",
    "UserBrowserInfoUpdateResp",
    "UserBrowserInfoDeleteParams",
    "UserBrowserInfoDeleteResp",
    "BrowserOpenUrlParams",
    "BrowserOpenUrlResp",
    "BrowserScreenshotParams",
    "BrowserScreenshotResp",
    "BrowserReleaseParams",
    "BrowserReleaseResp",
]
