"""initial baseline - create all tables

Revision ID: 21f94edb9f0b
Revises: 
Create Date: 2026-05-14 00:33:50.367108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21f94edb9f0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('action_type', sa.Enum('NAVIGATION', 'CLICK', 'INPUT', 'SCROLL', 'HOVER', 'WAIT', 'SCREENSHOT', 'EVALUATE', 'SELECT', 'KEYBOARD', 'MOUSE', 'LLM', 'LOOP', 'IF_ELSE', 'CUSTOM', 'COMPOSITE', name='actiontype'), nullable=False),
    sa.Column('parameters_schema', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('is_composite', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('user_data', sa.JSON(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retry_on_error', sa.Boolean(), nullable=False),
    sa.Column('retry_times', sa.Integer(), nullable=False),
    sa.Column('retry_delay', sa.Float(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('forked_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['custom_action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_action_name_unique', 'custom_action', ['mid', 'name'], unique=True)
    op.create_index(op.f('ix_custom_action_action_id'), 'custom_action', ['action_id'], unique=True)
    op.create_index(op.f('ix_custom_action_mid'), 'custom_action', ['mid'], unique=False)
    op.create_table('notificationconfig',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('browser_id', sa.BIGINT(), nullable=True),
    sa.Column('hitokoto', sa.Boolean(), nullable=False),
    sa.Column('bark_push', sa.Text(), nullable=True),
    sa.Column('bark_archive', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('bark_group', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('bark_sound', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('bark_icon', sa.Text(), nullable=True),
    sa.Column('bark_level', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('bark_url', sa.Text(), nullable=True),
    sa.Column('dd_bot_secret', sa.Text(), nullable=True),
    sa.Column('dd_bot_token', sa.Text(), nullable=True),
    sa.Column('fskey', sa.Text(), nullable=True),
    sa.Column('gobot_url', sa.Text(), nullable=True),
    sa.Column('gobot_qq', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('gobot_token', sa.Text(), nullable=True),
    sa.Column('gotify_url', sa.Text(), nullable=True),
    sa.Column('gotify_token', sa.Text(), nullable=True),
    sa.Column('gotify_priority', sa.Integer(), nullable=False),
    sa.Column('igot_push_key', sa.Text(), nullable=True),
    sa.Column('push_key', sa.Text(), nullable=True),
    sa.Column('deer_key', sa.Text(), nullable=True),
    sa.Column('deer_url', sa.Text(), nullable=True),
    sa.Column('chat_url', sa.Text(), nullable=True),
    sa.Column('chat_token', sa.Text(), nullable=True),
    sa.Column('push_plus_token', sa.Text(), nullable=True),
    sa.Column('push_plus_user', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('push_plus_template', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('push_plus_channel', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('push_plus_webhook', sa.Text(), nullable=True),
    sa.Column('push_plus_callbackurl', sa.Text(), nullable=True),
    sa.Column('push_plus_to', sa.Text(), nullable=True),
    sa.Column('we_plus_bot_token', sa.Text(), nullable=True),
    sa.Column('we_plus_bot_receiver', sa.Text(), nullable=True),
    sa.Column('we_plus_bot_version', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('qmsg_key', sa.Text(), nullable=True),
    sa.Column('qmsg_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('qywx_origin', sa.Text(), nullable=True),
    sa.Column('qywx_am', sa.Text(), nullable=True),
    sa.Column('qywx_key', sa.Text(), nullable=True),
    sa.Column('tg_bot_token', sa.Text(), nullable=True),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('tg_api_host', sa.Text(), nullable=True),
    sa.Column('tg_proxy_auth', sa.Text(), nullable=True),
    sa.Column('tg_proxy_host', sa.Text(), nullable=True),
    sa.Column('tg_proxy_port', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('aibotk_key', sa.Text(), nullable=True),
    sa.Column('aibotk_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('aibotk_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('smtp_server', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('smtp_ssl', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('smtp_email', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('pushme_key', sa.Text(), nullable=True),
    sa.Column('pushme_url', sa.Text(), nullable=True),
    sa.Column('chronocat_qq', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('chronocat_token', sa.Text(), nullable=True),
    sa.Column('chronocat_url', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('webhook_body', sa.Text(), nullable=True),
    sa.Column('webhook_headers', sa.Text(), nullable=True),
    sa.Column('webhook_method', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('webhook_content_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ntfy_url', sa.Text(), nullable=True),
    sa.Column('ntfy_topic', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ntfy_priority', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ntfy_token', sa.Text(), nullable=True),
    sa.Column('ntfy_username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ntfy_password', sa.Text(), nullable=True),
    sa.Column('ntfy_actions', sa.Text(), nullable=True),
    sa.Column('wxpusher_app_token', sa.Text(), nullable=True),
    sa.Column('wxpusher_topic_ids', sa.Text(), nullable=True),
    sa.Column('wxpusher_uids', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_notificationconfig_browser_id'), 'notificationconfig', ['browser_id'], unique=False)
    op.create_index(op.f('ix_notificationconfig_mid'), 'notificationconfig', ['mid'], unique=False)
    op.create_table('user_plugin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('custom_action_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hook_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('forked_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['user_plugin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_plugin_name_unique', 'user_plugin', ['mid', 'name'], unique=True)
    op.create_index(op.f('ix_user_plugin_mid'), 'user_plugin', ['mid'], unique=False)
    op.create_index(op.f('ix_user_plugin_plugin_id'), 'user_plugin', ['plugin_id'], unique=True)
    op.create_table('user_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('on_error', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('user_data', sa.JSON(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('forked_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['user_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_workflow_name_unique', 'user_workflow', ['mid', 'name'], unique=True)
    op.create_index(op.f('ix_user_workflow_mid'), 'user_workflow', ['mid'], unique=False)
    op.create_index(op.f('ix_user_workflow_workflow_id'), 'user_workflow', ['workflow_id'], unique=True)
    op.create_table('userbrowserdefaultsetting',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('default_proxy_server', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_platform', sa.Enum('windows', 'linux', 'macos', name='platformenum'), nullable=True),
    sa.Column('default_browser', sa.Enum('chrome', 'Edge', 'Opera', 'Vivaldi', name='browserenum'), nullable=True),
    sa.Column('default_lang', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('default_timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('default_viewport_width', sa.Integer(), nullable=True),
    sa.Column('default_viewport_height', sa.Integer(), nullable=True),
    sa.Column('default_timeout', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userbrowserdefaultsetting_mid'), 'userbrowserdefaultsetting', ['mid'], unique=False)
    op.create_table('userbrowserinfo',
    sa.Column('fingerprint', sa.Integer(), nullable=False),
    sa.Column('fingerprint_platform', sa.Enum('windows', 'linux', 'macos', name='platformenum'), nullable=True),
    sa.Column('fingerprint_platform_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_browser', sa.Enum('chrome', 'Edge', 'Opera', 'Vivaldi', name='browserenum'), nullable=True),
    sa.Column('fingerprint_brand_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_hardware_concurrency', sa.Integer(), nullable=True),
    sa.Column('fingerprint_gpu_vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_gpu_renderer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accept_lang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proxy_server', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patchright_screen_width', sa.Integer(), nullable=False),
    sa.Column('patchright_screen_height', sa.Integer(), nullable=False),
    sa.Column('patchright_viewport_width', sa.Integer(), nullable=False),
    sa.Column('patchright_viewport_height', sa.Integer(), nullable=False),
    sa.Column('patchright_fingerprint_dict', sa.JSON(), nullable=True),
    sa.Column('patchright_browser_ua', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('custom_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_userbrowserinfo_mid'), 'userbrowserinfo', ['mid'], unique=False)
    op.create_table('workflow_execution_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('browser_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.Column('steps_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('user_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_execution_log_browser_id'), 'workflow_execution_log', ['browser_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_log_execution_id'), 'workflow_execution_log', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_log_mid'), 'workflow_execution_log', ['mid'], unique=False)
    op.create_index(op.f('ix_workflow_execution_log_session_id'), 'workflow_execution_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_log_workflow_id'), 'workflow_execution_log', ['workflow_id'], unique=False)
    op.create_table('action_plugin_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['custom_action.action_id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['user_plugin.plugin_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plugin_link_action_id'), 'action_plugin_link', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_plugin_link_plugin_id'), 'action_plugin_link', ['plugin_id'], unique=False)
    op.create_table('workflow_plugin_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['user_plugin.plugin_id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['user_workflow.workflow_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_plugin_link_plugin_id'), 'workflow_plugin_link', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_workflow_plugin_link_workflow_id'), 'workflow_plugin_link', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_plugin_link_workflow_id'), table_name='workflow_plugin_link')
    op.drop_index(op.f('ix_workflow_plugin_link_plugin_id'), table_name='workflow_plugin_link')
    op.drop_table('workflow_plugin_link')
    op.drop_index(op.f('ix_action_plugin_link_plugin_id'), table_name='action_plugin_link')
    op.drop_index(op.f('ix_action_plugin_link_action_id'), table_name='action_plugin_link')
    op.drop_table('action_plugin_link')
    op.drop_index(op.f('ix_workflow_execution_log_workflow_id'), table_name='workflow_execution_log')
    op.drop_index(op.f('ix_workflow_execution_log_session_id'), table_name='workflow_execution_log')
    op.drop_index(op.f('ix_workflow_execution_log_mid'), table_name='workflow_execution_log')
    op.drop_index(op.f('ix_workflow_execution_log_execution_id'), table_name='workflow_execution_log')
    op.drop_index(op.f('ix_workflow_execution_log_browser_id'), table_name='workflow_execution_log')
    op.drop_table('workflow_execution_log')
    op.drop_index(op.f('ix_userbrowserinfo_mid'), table_name='userbrowserinfo')
    op.drop_table('userbrowserinfo')
    op.drop_index(op.f('ix_userbrowserdefaultsetting_mid'), table_name='userbrowserdefaultsetting')
    op.drop_table('userbrowserdefaultsetting')
    op.drop_index(op.f('ix_user_workflow_workflow_id'), table_name='user_workflow')
    op.drop_index(op.f('ix_user_workflow_mid'), table_name='user_workflow')
    op.drop_index('idx_user_workflow_name_unique', table_name='user_workflow')
    op.drop_table('user_workflow')
    op.drop_index(op.f('ix_user_plugin_plugin_id'), table_name='user_plugin')
    op.drop_index(op.f('ix_user_plugin_mid'), table_name='user_plugin')
    op.drop_index('idx_user_plugin_name_unique', table_name='user_plugin')
    op.drop_table('user_plugin')
    op.drop_index(op.f('ix_notificationconfig_mid'), table_name='notificationconfig')
    op.drop_index(op.f('ix_notificationconfig_browser_id'), table_name='notificationconfig')
    op.drop_table('notificationconfig')
    op.drop_index(op.f('ix_custom_action_mid'), table_name='custom_action')
    op.drop_index(op.f('ix_custom_action_action_id'), table_name='custom_action')
    op.drop_index('idx_user_action_name_unique', table_name='custom_action')
    op.drop_table('custom_action')
    # ### end Alembic commands ###
