"""Auto-generated migration (development mode)

Revision ID: 266dcb6db613
Revises: 5b8553fa215b
Create Date: 2026-06-29 14:58:51.791391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '266dcb6db613'
down_revision: Union[str, Sequence[str], None] = '5b8553fa215b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actionexecutionlog', 'action_type',
               existing_type=mysql.ENUM('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'LOOP', 'COMPOSITE', 'IF_ELSE', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'GET_TEXT', 'GET_WINDOW', 'FETCH_EXTERNAL_DATA', 'PRINT', 'LOOP', 'COMPOSITE', 'IF_ELSE', name='builtinactiontype'),
               existing_nullable=False)
    op.alter_column('compositeactionmodel', 'action_type',
               existing_type=mysql.ENUM('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'LOOP', 'COMPOSITE', 'IF_ELSE', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'GET_TEXT', 'GET_WINDOW', 'FETCH_EXTERNAL_DATA', 'PRINT', 'LOOP', 'COMPOSITE', 'IF_ELSE', name='builtinactiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compositeactionmodel', 'action_type',
               existing_type=sa.Enum('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'GET_TEXT', 'GET_WINDOW', 'FETCH_EXTERNAL_DATA', 'PRINT', 'LOOP', 'COMPOSITE', 'IF_ELSE', name='builtinactiontype'),
               type_=mysql.ENUM('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'LOOP', 'COMPOSITE', 'IF_ELSE', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('actionexecutionlog', 'action_type',
               existing_type=sa.Enum('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'GET_TEXT', 'GET_WINDOW', 'FETCH_EXTERNAL_DATA', 'PRINT', 'LOOP', 'COMPOSITE', 'IF_ELSE', name='builtinactiontype'),
               type_=mysql.ENUM('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'LOOP', 'COMPOSITE', 'IF_ELSE', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
