"""remove_community_like_report

Revision ID: 2cc1b2b4ca71
Revises: 19ac53b7d4f0
Create Date: 2026-08-16 14:44:48.961209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cc1b2b4ca71'
down_revision: Union[str, Sequence[str], None] = '19ac53b7d4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_unique_report'), table_name='resourcereport')
    op.drop_index(op.f('ix_resourcereport_mid'), table_name='resourcereport')
    op.drop_index(op.f('ix_resourcereport_resource_id'), table_name='resourcereport')
    op.drop_index(op.f('ix_resourcereport_resource_type'), table_name='resourcereport')
    op.drop_table('resourcereport')
    op.drop_index(op.f('idx_unique_like'), table_name='resourcelike')
    op.drop_index(op.f('ix_resourcelike_mid'), table_name='resourcelike')
    op.drop_index(op.f('ix_resourcelike_resource_id'), table_name='resourcelike')
    op.drop_index(op.f('ix_resourcelike_resource_type'), table_name='resourcelike')
    op.drop_table('resourcelike')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resourcelike',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('resource_type', mysql.ENUM('CUSTOM_ACTION', 'USER_WORKFLOW', 'USER_PLUGIN'), nullable=False),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resourcelike_resource_type'), 'resourcelike', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resourcelike_resource_id'), 'resourcelike', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resourcelike_mid'), 'resourcelike', ['mid'], unique=False)
    op.create_index(op.f('idx_unique_like'), 'resourcelike', ['mid', 'resource_type', 'resource_id'], unique=True)
    op.create_table('resourcereport',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('resource_type', mysql.ENUM('CUSTOM_ACTION', 'USER_WORKFLOW', 'USER_PLUGIN'), nullable=False),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.ENUM('SPAM', 'INAPPROPRIATE', 'VIOLATION', 'PLAGIARISM', 'OTHER'), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('reviewed_by_mid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('decision', mysql.ENUM('PENDING', 'IGNORED', 'WARNED', 'TAKEDOWN'), nullable=False),
    sa.Column('review_note', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resourcereport_resource_type'), 'resourcereport', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resourcereport_resource_id'), 'resourcereport', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resourcereport_mid'), 'resourcereport', ['mid'], unique=False)
    op.create_index(op.f('idx_unique_report'), 'resourcereport', ['mid', 'resource_type', 'resource_id'], unique=False)
    # ### end Alembic commands ###
