"""Auto-generated migration (development mode)

Revision ID: 5b8553fa215b
Revises: 86c05e39b054
Create Date: 2026-06-25 12:40:59.277960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b8553fa215b'
down_revision: Union[str, Sequence[str], None] = '86c05e39b054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tagmodel_name'), 'tagmodel', ['name'], unique=True)
    op.create_table('compositeactiontaglink',
    sa.Column('composite_action_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composite_action_id'], ['compositeactionmodel.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tagmodel.id'], ),
    sa.PrimaryKeyConstraint('composite_action_id', 'tag_id')
    )
    op.drop_column('compositeactionmodel', 'author')
    op.drop_column('compositeactionmodel', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compositeactionmodel', sa.Column('tags', mysql.JSON(), nullable=True))
    op.add_column('compositeactionmodel', sa.Column('author', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_table('compositeactiontaglink')
    op.drop_index(op.f('ix_tagmodel_name'), table_name='tagmodel')
    op.drop_table('tagmodel')
    # ### end Alembic commands ###
