"""Auto-generated migration (development mode)

Revision ID: 86c05e39b054
Revises: 
Create Date: 2026-06-06 19:02:18.972418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86c05e39b054'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionexecutionlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parent_execution_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('action_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('action_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('action_type', sa.Enum('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'LOOP', 'COMPOSITE', 'IF_ELSE', name='builtinactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'CANCELLED', name='executionstatus'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actionexecutionlog_action_id'), 'actionexecutionlog', ['action_id'], unique=False)
    op.create_index(op.f('ix_actionexecutionlog_execution_id'), 'actionexecutionlog', ['execution_id'], unique=False)
    op.create_index(op.f('ix_actionexecutionlog_mid'), 'actionexecutionlog', ['mid'], unique=False)
    op.create_index(op.f('ix_actionexecutionlog_workflow_id'), 'actionexecutionlog', ['workflow_id'], unique=False)
    op.create_table('compositeactionmodel',
    sa.Column('mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('action_type', sa.Enum('CLICK', 'INPUT', 'WAIT', 'SCROLL', 'NAVIGATE', 'SCREENSHOT', 'LLM', 'HOVER', 'NEW_PAGE', 'LOOP', 'COMPOSITE', 'IF_ELSE', name='builtinactiontype'), nullable=False),
    sa.Column('parameters_schema', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('is_composite', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('input_vars', sa.JSON(), nullable=True),
    sa.Column('output_vars', sa.JSON(), nullable=True),
    sa.Column('forked_from_id', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retry_on_error', sa.Boolean(), nullable=False),
    sa.Column('retry_times', sa.Integer(), nullable=False),
    sa.Column('retry_delay', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['compositeactionmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_action_name_unique', 'compositeactionmodel', ['mid', 'name'], unique=True)
    op.create_index(op.f('ix_compositeactionmodel_action_id'), 'compositeactionmodel', ['action_id'], unique=True)
    op.create_index(op.f('ix_compositeactionmodel_mid'), 'compositeactionmodel', ['mid'], unique=False)
    op.create_index(op.f('ix_compositeactionmodel_original_mid'), 'compositeactionmodel', ['original_mid'], unique=False)
    op.create_table('notificationconfig',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('browser_id', sa.BIGINT(), nullable=True),
    sa.Column('hitokoto', sa.Boolean(), nullable=False),
    sa.Column('bark_push', sa.Text(), nullable=True),
    sa.Column('bark_archive', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('bark_group', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('bark_sound', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('bark_icon', sa.Text(), nullable=True),
    sa.Column('bark_level', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('bark_url', sa.Text(), nullable=True),
    sa.Column('dd_bot_secret', sa.Text(), nullable=True),
    sa.Column('dd_bot_token', sa.Text(), nullable=True),
    sa.Column('fskey', sa.Text(), nullable=True),
    sa.Column('gobot_url', sa.Text(), nullable=True),
    sa.Column('gobot_qq', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('gobot_token', sa.Text(), nullable=True),
    sa.Column('gotify_url', sa.Text(), nullable=True),
    sa.Column('gotify_token', sa.Text(), nullable=True),
    sa.Column('gotify_priority', sa.Integer(), nullable=False),
    sa.Column('igot_push_key', sa.Text(), nullable=True),
    sa.Column('push_key', sa.Text(), nullable=True),
    sa.Column('deer_key', sa.Text(), nullable=True),
    sa.Column('deer_url', sa.Text(), nullable=True),
    sa.Column('chat_url', sa.Text(), nullable=True),
    sa.Column('chat_token', sa.Text(), nullable=True),
    sa.Column('push_plus_token', sa.Text(), nullable=True),
    sa.Column('push_plus_user', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('push_plus_template', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('push_plus_channel', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('push_plus_webhook', sa.Text(), nullable=True),
    sa.Column('push_plus_callbackurl', sa.Text(), nullable=True),
    sa.Column('push_plus_to', sa.Text(), nullable=True),
    sa.Column('we_plus_bot_token', sa.Text(), nullable=True),
    sa.Column('we_plus_bot_receiver', sa.Text(), nullable=True),
    sa.Column('we_plus_bot_version', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('qmsg_key', sa.Text(), nullable=True),
    sa.Column('qmsg_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('qywx_origin', sa.Text(), nullable=True),
    sa.Column('qywx_am', sa.Text(), nullable=True),
    sa.Column('qywx_key', sa.Text(), nullable=True),
    sa.Column('tg_bot_token', sa.Text(), nullable=True),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('tg_api_host', sa.Text(), nullable=True),
    sa.Column('tg_proxy_auth', sa.Text(), nullable=True),
    sa.Column('tg_proxy_host', sa.Text(), nullable=True),
    sa.Column('tg_proxy_port', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('aibotk_key', sa.Text(), nullable=True),
    sa.Column('aibotk_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('aibotk_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('smtp_server', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('smtp_ssl', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('smtp_email', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('pushme_key', sa.Text(), nullable=True),
    sa.Column('pushme_url', sa.Text(), nullable=True),
    sa.Column('chronocat_qq', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('chronocat_token', sa.Text(), nullable=True),
    sa.Column('chronocat_url', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('webhook_body', sa.Text(), nullable=True),
    sa.Column('webhook_headers', sa.Text(), nullable=True),
    sa.Column('webhook_method', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('webhook_content_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ntfy_url', sa.Text(), nullable=True),
    sa.Column('ntfy_topic', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ntfy_priority', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ntfy_token', sa.Text(), nullable=True),
    sa.Column('ntfy_username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ntfy_password', sa.Text(), nullable=True),
    sa.Column('ntfy_actions', sa.Text(), nullable=True),
    sa.Column('wxpusher_app_token', sa.Text(), nullable=True),
    sa.Column('wxpusher_topic_ids', sa.Text(), nullable=True),
    sa.Column('wxpusher_uids', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_notificationconfig_browser_id'), 'notificationconfig', ['browser_id'], unique=False)
    op.create_index(op.f('ix_notificationconfig_mid'), 'notificationconfig', ['mid'], unique=False)
    op.create_table('resourcelike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('CUSTOM_ACTION', 'USER_WORKFLOW', 'USER_PLUGIN', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_like', 'resourcelike', ['mid', 'resource_type', 'resource_id'], unique=True)
    op.create_index(op.f('ix_resourcelike_mid'), 'resourcelike', ['mid'], unique=False)
    op.create_index(op.f('ix_resourcelike_resource_id'), 'resourcelike', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resourcelike_resource_type'), 'resourcelike', ['resource_type'], unique=False)
    op.create_table('resourcereport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('CUSTOM_ACTION', 'USER_WORKFLOW', 'USER_PLUGIN', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'INAPPROPRIATE', 'VIOLATION', 'PLAGIARISM', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_report', 'resourcereport', ['mid', 'resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_resourcereport_mid'), 'resourcereport', ['mid'], unique=False)
    op.create_index(op.f('ix_resourcereport_resource_id'), 'resourcereport', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resourcereport_resource_type'), 'resourcereport', ['resource_type'], unique=False)
    op.create_table('userbrowserdefaultsetting',
    sa.Column('browser_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('default_proxy_server', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_platform', sa.Enum('windows', 'linux', 'macos', name='platformenum'), nullable=True),
    sa.Column('default_browser', sa.Enum('chrome', 'Edge', 'Opera', 'Vivaldi', name='browserenum'), nullable=True),
    sa.Column('default_lang', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('default_timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('default_viewport_width', sa.Integer(), nullable=True),
    sa.Column('default_viewport_height', sa.Integer(), nullable=True),
    sa.Column('default_timeout', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('browser_id')
    )
    op.create_index(op.f('ix_userbrowserdefaultsetting_mid'), 'userbrowserdefaultsetting', ['mid'], unique=False)
    op.create_table('userbrowserinfo',
    sa.Column('fingerprint', sa.Integer(), nullable=False),
    sa.Column('fingerprint_platform', sa.Enum('windows', 'linux', 'macos', name='platformenum'), nullable=True),
    sa.Column('fingerprint_platform_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_browser', sa.Enum('chrome', 'Edge', 'Opera', 'Vivaldi', name='browserenum'), nullable=True),
    sa.Column('fingerprint_brand_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_hardware_concurrency', sa.Integer(), nullable=True),
    sa.Column('fingerprint_gpu_vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_gpu_renderer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accept_lang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proxy_server', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patchright_screen_width', sa.Integer(), nullable=False),
    sa.Column('patchright_screen_height', sa.Integer(), nullable=False),
    sa.Column('patchright_viewport_width', sa.Integer(), nullable=False),
    sa.Column('patchright_viewport_height', sa.Integer(), nullable=False),
    sa.Column('patchright_fingerprint_dict', sa.JSON(), nullable=True),
    sa.Column('patchright_browser_ua', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('browser_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('custom_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('browser_id'),
    sa.UniqueConstraint('fingerprint'),
    sa.UniqueConstraint('mid', 'custom_name', name='uq_mid_custom_name')
    )
    op.create_index(op.f('ix_userbrowserinfo_mid'), 'userbrowserinfo', ['mid'], unique=False)
    op.create_table('userplugin',
    sa.Column('mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('custom_action_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hook_type', sa.Enum('BEFORE_ACTION', 'AFTER_ACTION', 'ON_SUCCESS', 'ON_ERROR', 'ON_TIMEOUT', name='pluginhookenum'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('forked_from_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['userplugin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_plugin_name_unique', 'userplugin', ['mid', 'name'], unique=True)
    op.create_index(op.f('ix_userplugin_mid'), 'userplugin', ['mid'], unique=False)
    op.create_index(op.f('ix_userplugin_original_mid'), 'userplugin', ['original_mid'], unique=False)
    op.create_index(op.f('ix_userplugin_plugin_id'), 'userplugin', ['plugin_id'], unique=True)
    op.create_table('userworkflow',
    sa.Column('mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('custom_action_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('forked_from_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['forked_from_id'], ['userworkflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_workflow_name_unique', 'userworkflow', ['mid', 'name'], unique=True)
    op.create_index(op.f('ix_userworkflow_custom_action_id'), 'userworkflow', ['custom_action_id'], unique=False)
    op.create_index(op.f('ix_userworkflow_mid'), 'userworkflow', ['mid'], unique=False)
    op.create_index(op.f('ix_userworkflow_original_mid'), 'userworkflow', ['original_mid'], unique=False)
    op.create_index(op.f('ix_userworkflow_workflow_id'), 'userworkflow', ['workflow_id'], unique=True)
    op.create_table('workflowexecutionlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('browser_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.Column('steps_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowexecutionlog_browser_id'), 'workflowexecutionlog', ['browser_id'], unique=False)
    op.create_index(op.f('ix_workflowexecutionlog_execution_id'), 'workflowexecutionlog', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflowexecutionlog_mid'), 'workflowexecutionlog', ['mid'], unique=False)
    op.create_index(op.f('ix_workflowexecutionlog_session_id'), 'workflowexecutionlog', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflowexecutionlog_workflow_id'), 'workflowexecutionlog', ['workflow_id'], unique=False)
    op.create_table('workflowrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('entry_action_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('params_template', sa.JSON(), nullable=True),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'SCHEDULED', 'EVENT', name='triggertype'), nullable=False),
    sa.Column('crontab_expression', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('mid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('forked_from_id', sa.Integer(), nullable=True),
    sa.Column('on_error', sa.Enum('STOP', 'CONTINUE', 'ROLLBACK', name='errorhandlingenum'), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['workflowrecord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_user_name_unique', 'workflowrecord', ['mid', 'name'], unique=True)
    op.create_index(op.f('ix_workflowrecord_mid'), 'workflowrecord', ['mid'], unique=False)
    op.create_index(op.f('ix_workflowrecord_workflow_id'), 'workflowrecord', ['workflow_id'], unique=True)
    op.create_table('workflowpluginrelation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['userplugin.plugin_id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['userworkflow.workflow_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowpluginrelation_plugin_id'), 'workflowpluginrelation', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_workflowpluginrelation_workflow_id'), 'workflowpluginrelation', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflowpluginrelation_workflow_id'), table_name='workflowpluginrelation')
    op.drop_index(op.f('ix_workflowpluginrelation_plugin_id'), table_name='workflowpluginrelation')
    op.drop_table('workflowpluginrelation')
    op.drop_index(op.f('ix_workflowrecord_workflow_id'), table_name='workflowrecord')
    op.drop_index(op.f('ix_workflowrecord_mid'), table_name='workflowrecord')
    op.drop_index('idx_workflow_user_name_unique', table_name='workflowrecord')
    op.drop_table('workflowrecord')
    op.drop_index(op.f('ix_workflowexecutionlog_workflow_id'), table_name='workflowexecutionlog')
    op.drop_index(op.f('ix_workflowexecutionlog_session_id'), table_name='workflowexecutionlog')
    op.drop_index(op.f('ix_workflowexecutionlog_mid'), table_name='workflowexecutionlog')
    op.drop_index(op.f('ix_workflowexecutionlog_execution_id'), table_name='workflowexecutionlog')
    op.drop_index(op.f('ix_workflowexecutionlog_browser_id'), table_name='workflowexecutionlog')
    op.drop_table('workflowexecutionlog')
    op.drop_index(op.f('ix_userworkflow_workflow_id'), table_name='userworkflow')
    op.drop_index(op.f('ix_userworkflow_original_mid'), table_name='userworkflow')
    op.drop_index(op.f('ix_userworkflow_mid'), table_name='userworkflow')
    op.drop_index(op.f('ix_userworkflow_custom_action_id'), table_name='userworkflow')
    op.drop_index('idx_user_workflow_name_unique', table_name='userworkflow')
    op.drop_table('userworkflow')
    op.drop_index(op.f('ix_userplugin_plugin_id'), table_name='userplugin')
    op.drop_index(op.f('ix_userplugin_original_mid'), table_name='userplugin')
    op.drop_index(op.f('ix_userplugin_mid'), table_name='userplugin')
    op.drop_index('idx_user_plugin_name_unique', table_name='userplugin')
    op.drop_table('userplugin')
    op.drop_index(op.f('ix_userbrowserinfo_mid'), table_name='userbrowserinfo')
    op.drop_table('userbrowserinfo')
    op.drop_index(op.f('ix_userbrowserdefaultsetting_mid'), table_name='userbrowserdefaultsetting')
    op.drop_table('userbrowserdefaultsetting')
    op.drop_index(op.f('ix_resourcereport_resource_type'), table_name='resourcereport')
    op.drop_index(op.f('ix_resourcereport_resource_id'), table_name='resourcereport')
    op.drop_index(op.f('ix_resourcereport_mid'), table_name='resourcereport')
    op.drop_index('idx_unique_report', table_name='resourcereport')
    op.drop_table('resourcereport')
    op.drop_index(op.f('ix_resourcelike_resource_type'), table_name='resourcelike')
    op.drop_index(op.f('ix_resourcelike_resource_id'), table_name='resourcelike')
    op.drop_index(op.f('ix_resourcelike_mid'), table_name='resourcelike')
    op.drop_index('idx_unique_like', table_name='resourcelike')
    op.drop_table('resourcelike')
    op.drop_index(op.f('ix_notificationconfig_mid'), table_name='notificationconfig')
    op.drop_index(op.f('ix_notificationconfig_browser_id'), table_name='notificationconfig')
    op.drop_table('notificationconfig')
    op.drop_index(op.f('ix_compositeactionmodel_original_mid'), table_name='compositeactionmodel')
    op.drop_index(op.f('ix_compositeactionmodel_mid'), table_name='compositeactionmodel')
    op.drop_index(op.f('ix_compositeactionmodel_action_id'), table_name='compositeactionmodel')
    op.drop_index('idx_user_action_name_unique', table_name='compositeactionmodel')
    op.drop_table('compositeactionmodel')
    op.drop_index(op.f('ix_actionexecutionlog_workflow_id'), table_name='actionexecutionlog')
    op.drop_index(op.f('ix_actionexecutionlog_mid'), table_name='actionexecutionlog')
    op.drop_index(op.f('ix_actionexecutionlog_execution_id'), table_name='actionexecutionlog')
    op.drop_index(op.f('ix_actionexecutionlog_action_id'), table_name='actionexecutionlog')
    op.drop_table('actionexecutionlog')
    # ### end Alembic commands ###
