"""recreate_resource_report

Revision ID: 8b23dd19f7aa
Revises: 2cc1b2b4ca71
Create Date: 2026-08-16 15:05:33.989441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b23dd19f7aa'
down_revision: Union[str, Sequence[str], None] = '2cc1b2b4ca71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resourcereport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.String(255), nullable=False),
    sa.Column('resource_type', sa.Enum('CUSTOM_ACTION', 'USER_WORKFLOW', 'USER_PLUGIN', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'INAPPROPRIATE', 'VIOLATION', 'PLAGIARISM', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('description', sa.String(500), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_mid', sa.String(255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('decision', sa.Enum('PENDING', 'IGNORED', 'WARNED', 'TAKEDOWN', name='reportdecision'), nullable=False),
    sa.Column('review_note', sa.String(500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_report', 'resourcereport', ['mid', 'resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_resourcereport_mid'), 'resourcereport', ['mid'], unique=False)
    op.create_index(op.f('ix_resourcereport_resource_id'), 'resourcereport', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resourcereport_resource_type'), 'resourcereport', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resourcereport_resource_type'), table_name='resourcereport')
    op.drop_index(op.f('ix_resourcereport_resource_id'), table_name='resourcereport')
    op.drop_index(op.f('ix_resourcereport_mid'), table_name='resourcereport')
    op.drop_index('idx_unique_report', table_name='resourcereport')
    op.drop_table('resourcereport')
    # ### end Alembic commands ###
