"""Auto-generated migration (development mode)

Revision ID: a75c00e3ba6f
Revises: 21f94edb9f0b
Create Date: 2026-05-18 01:08:05.522213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a75c00e3ba6f'
down_revision: Union[str, Sequence[str], None] = '21f94edb9f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbrowserdefaultsetting', sa.Column('browser_id', sa.BIGINT(), nullable=False))
    op.drop_column('userbrowserdefaultsetting', 'id')
    op.add_column('userbrowserinfo', sa.Column('browser_id', sa.BIGINT(), nullable=False))
    op.drop_column('userbrowserinfo', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbrowserinfo', sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False))
    op.drop_column('userbrowserinfo', 'browser_id')
    op.add_column('userbrowserdefaultsetting', sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False))
    op.drop_column('userbrowserdefaultsetting', 'browser_id')
    # ### end Alembic commands ###
