"""
Models 模块 - 数据模型统一入口

按照业务模块划分的模型层结构：
├── __init__.py          - 模块入口，统一导出
├── base/                - 基础模型
│   ├── __init__.py
│   └── base_sqlmodel.py
├── common/              - 通用响应和异常
│   ├── __init__.py
│   ├── response.py
│   ├── response_code.py
│   ├── response_msg.py
│   └── exceptions/
│       └── base_exception.py
├── core/                - 核心业务模型（浏览器指纹、信息）
│   ├── __init__.py
│   ├── fingerprint.py
│   ├── browser_info.py
│   └── browser_exec.py
├── plugin/             - 插件模型
│   ├── __init__.py
│   ├── enums.py
│   ├── models.py
│   └── request_models.py
├── notify/             - 通知模型
│   ├── __init__.py
│   ├── models.py
│   ├── request_models.py
│   └── response_models.py
├── workflow/           - 工作流模型
│   ├── __init__.py
│   └── models.py
├── runtime/            - 运行时模型（会话、控制、视频流）
│   ├── __init__.py
│   ├── session.py
│   ├── control.py
│   ├── webrtc.py
│   ├── operations.py
│   ├── api.py
│   └── simplified.py
├── router/             - 路由配置模型
│   ├── __init__.py
│   ├── prefix.py
│   ├── tag.py
│   └── routes.py
└── system/             - 系统模型（管理员、权限）
    ├── __init__.py
    ├── admin.py
    └── permission.py
"""

# ============ Base 模块 ============
from app.models.base import BaseSQLModel, BasePaginationReq, BasePaginationResp

# ============ Common 模块 ============
from app.models.common import (
    ResponseCode,
    ResponseMsg,
    StandardResponse,
    success_response,
    error_response,
    custom_response,
    DataT,
    BaseException,
    BrowserNotifyConfNotFoundException,
    BrowserIdIsNoneExeception,
    BrowserIdNotBeloneToUserException,
    NotLoggedInException,
    InvalidUIDException,
    InvalidMidFormatException,
    PluginIdIsNoneException,
    PluginIdNotBelongToUserException,
    BrowserNotStartedException,
    VideoStreamInitFailedException,
    GetBrowserSessionFailedException,
    BrowserFingerprintNotFoundException,
    FingerprintLimitExceededException,
    AuthInfo,
    VerifyBrowserDependsReq,
    VerifyFingerprintDependsReq,
    BrowserReqInfo,
    BrowserReqAuthInfo,
    VerifyPluginDependsReq,
    BrowserPluginReqInfo,
)

# ============ Core 模块 ============
from app.models.core import (
    PlatformEnum,
    BrowserEnum,
    Int32,
    BaseFingerprintBrowserInitParams,
    UserBrowserToken,
    UserBrowserInfoBase,
    UserBrowserServerSideDefaultSetting,
    UserBrowserDefaultSetting,
    UserBrowserInfoWithoutPlugin,
    UserBrowserInfo,
    UserBrowserDefaultSettingRequest,
    UserBrowserDefaultSettingResponse,
    BrowserExecInfoModel,
    BrowserExecInfoModels,
)

# ============ Plugin 模块 ============
from app.models.plugin import (
    LogPluginLogLevelEnum,
    PluginBaseModel,
    PluginBaseModelWithoutMid,
    LogPluginModel,
    PageLimitPluginModel,
    RandomWaitPluginModel,
    RetryPluginModel,
    LogPluginCreate,
    PageLimitPluginCreate,
    RandomWaitPluginCreate,
    RetryPluginCreate,
    PluginCreateRequest,
    PluginGetRequest,
    PluginListRequest,
    PluginDeleteRequest,
    PluginUpdateRequest,
    PluginResponse,
    LogPluginResponse,
    PageLimitPluginResponse,
    RandomWaitPluginResponse,
    RetryPluginResponse,
    PluginDictResponse,
    LogPluginConfig,
    PageLimitPluginConfig,
    RandomWaitPluginConfig,
    RetryPluginConfig,
    DEFAULT_PLUGIN_CONFIGS,
    get_default_plugin_config,
    is_plugin_config_changed,
    get_plugin_config_diff,
)

# ============ Notify 模块 ============
from app.models.notify import (
    NotificationConfigBase,
    NotificationConfig,
    NotificationConfigCreate,
    NotificationConfigUpdate,
    NotifyConfigReadRequest,
    BrowserEffectiveNotifyRequest,
    TestNotificationRequest,
    TestNotificationResponse,
    NotificationConfigUpsertResp,
    NotificationConfigDeleteResp,
    NotificationConfigEffectiveResp,
)

# ============ Workflow 模块 ============
from app.models.workflow import (
    ActionTypeEnum,
    ErrorHandlingEnum,
    PluginHookEnum,
    WorkflowStepModel,
    CustomActionModel,
    UserPluginModel,
    UserWorkflowModel,
    WorkflowExecutionLogModel,
    WorkflowStepRequest,
    WorkflowCreateRequest,
    WorkflowUpdateRequest,
    WorkflowListRequest,
    WorkflowExecuteRequest,
    WorkflowDetailResponse,
    WorkflowListItemResponse,
    WorkflowCreateResponse,
    WorkflowDuplicateResponse,
    WorkflowExecuteResponse,
    CustomActionCreateRequest,
    CustomActionUpdateRequest,
    CustomActionDetailResponse,
    CustomActionListItemResponse,
    CustomActionCreateResponse,
    ActionExecuteRequest,
    BatchActionRequest,
    ActionPreviewRequest,
    ActionValidateRequest,
    ExecuteStepRequest,
    ActionResultResponse,
    StepPreviewItem,
    ActionPreviewResponse,
    ActionValidateResponse,
    ExecuteStepResponse,
    ActionParameterResponse,
    ActionMetadataResponse,
    ReloadActionsResponse,
)

# ============ Runtime 模块 ============
from app.models.runtime import (
    BrowserSessionBaseParams,
    BrowserSessionGetParams,
    BrowserSessionCreateParams,
    BrowserSessionAllRemoveParams,
    BrowserSessionRemoveParams,
    SessionCreateParams,
    SessionCloseResponse,
    SessionAllCloseResponse,
    BrowserStatusEnum,
    VideoStreamStatusEnum,
    OperationPriority,
    BrowserStatus,
    LiveControlCommand,
    VideoStreamParams,
    VideoStreamStatus,
    VideoStreamResponse,
    HeartbeatRequest,
    HeartbeatResponse,
    ManualOperationRequest,
    AutomationResumeRequest,
    BrowserCleanupPolicy,
    SessionLifecycleState,
    BrowserSessionStatus,
    CreateSessionRequest,
    CreateSessionResponse,
    BrowserIdParam,
    VideoStreamStatusRequest,
    VideoStreamMjpegRequest,
    ScreenshotRequest,
    BrowserStatusRequest,
    NavigateRequest,
    JavaScriptExecuteRequest,
    BrowserClickRequest,
    JavaScriptExecuteWithParamsRequest,
    ForceReleaseRequest,
    HeartbeatWithBrowserIdRequest,
    CreateSessionWithBrowserIdRequest,
    ManualOperationWithBrowserIdRequest,
    AutomationResumeWithBrowserIdRequest,
    BrowserCleanupPolicyRequest,
    LiveControlCommandWithBrowserId,
    StartVideoStreamRequest,
    BrowserOperationRequest,
    PausePluginsRequest,
    ManualOperationResponse,
    AutomationResumeResponse,
    OperationStatusResponse,
    PluginStatusResponse,
    BrowserInfoResponse,
    VideoStreamStatusResponse,
    SystemStatisticsResponse,
    CleanupPolicyResponse,
    SystemCleanupResponse,
    ForceReleaseResponse,
    SystemHealthCheckResponse,
    EmptyRequest,
    BrowserInfoData,
    VideoStreamStatusData,
    ManualOperationResult,
    AutomationResult,
    OperationStatusData,
    PluginStatusData,
    SessionStatisticsData,
    CreateSessionData,
    BrowserSessionStatusData,
    JavaScriptExecutionResult,
    ModelInfo,
    ChineseClickPredictionDetail,
    WebRTCOfferResponse,
    WebRTCAnswerRequest,
    WebRTCAnswerResponse,
    WebRTCIceCandidateRequest,
    WebRTCIceCandidateResponse,
    WebRTCGetIceCandidatesResponse,
    WebRTCConnectionStatusResponse,
    WebRTCCloseConnectionResponse,
    RPAClickParams,
    BrowserClickParams,
    ClickResponse,
    RPAFillParams,
    RPAScrollParams,
    RPAEvaluateParams,
    RPAScreenshotParams,
    RPAWaitParams,
    RPANavigateParams,
    JavaScriptExecuteParams,
    ExecuteJsResponse,
    SecurityCheckParams,
    SecurityRisk,
    SecurityCheckResult,
    RPAResponse,
    BrowserFingerprintCreateParams,
    BrowserFingerprintUpdateParams,
    BrowserFingerprintUpsertParams,
    BrowserFingerprintQueryParams,
    BrowserFingerprintDeleteParams,
    BrowserFingerprintListParams,
    BrowserFingerprintRenameParams,
    BrowserFingerprintCreateResp,
    BrowserFingerprintUpdateResp,
    BrowserFingerprintDeleteResp,
    BrowserFingerprintRenameResp,
    BrowserFingerprintQueryResp,
    BrowserOperationOpenUrlParams,
    BrowserOperationScreenshotParams,
    BrowserOperationReleaseParams,
    BrowserOperationOpenUrlResp,
    BrowserOperationScreenshotResp,
    BrowserOperationReleaseResp,
    SimplifiedHeartbeatRequest,
    SimplifiedCreateSessionRequest,
    SimplifiedManualOperationRequest,
    SimplifiedAutomationResumeRequest,
    SimplifiedLiveControlCommand,
    SimplifiedStartVideoStreamRequest,
    SimplifiedBrowserCleanupPolicyRequest,
    SimplifiedScreenshotRequest,
    SimplifiedNavigateRequest,
    SimplifiedJavaScriptExecuteRequest,
    SimplifiedBrowserClickRequest,
    SimplifiedJavaScriptExecuteWithParamsRequest,
    SimplifiedExecuteJSRequest,
    SimplifiedVideoStreamMjpegRequest,
    SimplifiedForceReleaseRequest,
    SimplifiedPausePluginsRequest,
)

# ============ Runtime - Live Service ============
from app.models.runtime.live_service import (
    BrowserSessionEntry,
    VideoStreamInfo,
    LiveStreamingEntry,
    LiveServiceState,
)

# ============ Router 模块 ============
from app.models.router import (
    RouterPrefix,
    BrowserFingerprintRouterPath,
    BrowserSessionRouterPath,
    BrowserControlRouterPath,
    PluginRouterPath,
    UserBrowserDefaultSettingRouterPath,
    NotifyRouterPath,
    RouterTag,
    VersionTag,
    RouterInfo,
    DEFAULT_VERSION,
    BROWSER_CONFIG_ROUTERS,
    BROWSER_RUNTIME_ROUTERS,
    SYSTEM_ROUTERS,
    ALL_ROUTERS,
    validate_router_uniqueness,
)

# ============ System 模块 ============
from app.models.system import (
    AdminSessionInfo,
    AdminAllSessionsResponse,
    AdminLiveStreamInfo,
    AdminWebRTCConnectionInfo,
    AdminAllStreamsResponse,
    AdminAllStatsResponse,
    PermissionLevelConfig,
    PermissionConfigList,
    PermissionConfigData,
)


# ============ 向后兼容别名 ============
# 这些别名用于保持与旧代码的兼容性
from app.models.runtime.api import (
    UserBrowserInfoCreateParams,
    UserBrowserInfoUpsertParams,
    UserBrowserInfoCreateResp,
    UserBrowserInfoCountParams,
    UserBrowserInfoListParams,
    UserBrowserInfoReadParams,
    UserBrowserInfoReadResp,
    UserBrowserInfoUpdateParams,
    UserBrowserInfoUpdateResp,
    UserBrowserInfoDeleteParams,
    UserBrowserInfoDeleteResp,
    BrowserOpenUrlParams,
    BrowserOpenUrlResp,
    BrowserScreenshotParams,
    BrowserScreenshotResp,
    BrowserReleaseParams,
    BrowserReleaseResp,
)
from app.models.runtime.control import StreamStatusResponse
from app.models.runtime.simplified import ExecuteJSResponse
from app.models.runtime.control import EmptyRequest


__all__ = [
    # Base
    "BaseSQLModel",
    "BasePaginationReq",
    "BasePaginationResp",
    # Common
    "ResponseCode",
    "ResponseMsg",
    "StandardResponse",
    "success_response",
    "error_response",
    "custom_response",
    "DataT",
    "BaseException",
    "BrowserNotifyConfNotFoundException",
    "BrowserIdIsNoneExeception",
    "BrowserIdNotBeloneToUserException",
    "NotLoggedInException",
    "InvalidUIDException",
    "InvalidMidFormatException",
    "PluginIdIsNoneException",
    "PluginIdNotBelongToUserException",
    "BrowserNotStartedException",
    "VideoStreamInitFailedException",
    "GetBrowserSessionFailedException",
    "BrowserFingerprintNotFoundException",
    "FingerprintLimitExceededException",
    # Depends
    "AuthInfo",
    "VerifyBrowserDependsReq",
    "VerifyFingerprintDependsReq",
    "BrowserReqInfo",
    "BrowserReqAuthInfo",
    "VerifyPluginDependsReq",
    "BrowserPluginReqInfo",
    # Core
    "PlatformEnum",
    "BrowserEnum",
    "Int32",
    "BaseFingerprintBrowserInitParams",
    "UserBrowserToken",
    "UserBrowserInfoBase",
    "UserBrowserServerSideDefaultSetting",
    "UserBrowserDefaultSetting",
    "UserBrowserInfoWithoutPlugin",
    "UserBrowserInfo",
    "UserBrowserDefaultSettingRequest",
    "UserBrowserDefaultSettingResponse",
    "BrowserExecInfoModel",
    "BrowserExecInfoModels",
    # Plugin
    "LogPluginLogLevelEnum",
    "PluginBaseModel",
    "PluginBaseModelWithoutMid",
    "LogPluginModel",
    "PageLimitPluginModel",
    "RandomWaitPluginModel",
    "RetryPluginModel",
    "PluginCreateRequest",
    "PluginGetRequest",
    "PluginListRequest",
    "PluginDeleteRequest",
    "PluginUpdateRequest",
    "PluginResponse",
    "LogPluginResponse",
    "PageLimitPluginResponse",
    "RandomWaitPluginResponse",
    "RetryPluginResponse",
    "PluginDictResponse",
    # Plugin Config
    "LogPluginConfig",
    "PageLimitPluginConfig",
    "RandomWaitPluginConfig",
    "RetryPluginConfig",
    "DEFAULT_PLUGIN_CONFIGS",
    "get_default_plugin_config",
    "is_plugin_config_changed",
    "get_plugin_config_diff",
    # Notify
    "NotificationConfigBase",
    "NotificationConfig",
    "NotificationConfigCreate",
    "NotificationConfigUpdate",
    "NotifyConfigReadRequest",
    "BrowserEffectiveNotifyRequest",
    "TestNotificationRequest",
    "TestNotificationResponse",
    "NotificationConfigUpsertResp",
    "NotificationConfigDeleteResp",
    "NotificationConfigEffectiveResp",
    # Workflow
    "ActionTypeEnum",
    "ErrorHandlingEnum",
    "PluginHookEnum",
    "WorkflowStepModel",
    "CustomActionModel",
    "UserPluginModel",
    "UserWorkflowModel",
    "WorkflowExecutionLogModel",
    "WorkflowStepRequest",
    "WorkflowCreateRequest",
    "WorkflowUpdateRequest",
    "WorkflowListRequest",
    "WorkflowExecuteRequest",
    "WorkflowDetailResponse",
    "WorkflowListItemResponse",
    "WorkflowCreateResponse",
    "WorkflowDuplicateResponse",
    "WorkflowExecuteResponse",
    "CustomActionCreateRequest",
    "CustomActionUpdateRequest",
    "CustomActionDetailResponse",
    "CustomActionListItemResponse",
    "CustomActionCreateResponse",
    "ActionExecuteRequest",
    "BatchActionRequest",
    "ActionPreviewRequest",
    "ActionValidateRequest",
    "ExecuteStepRequest",
    "ActionResultResponse",
    "StepPreviewItem",
    "ActionPreviewResponse",
    "ActionValidateResponse",
    "ExecuteStepResponse",
    "ActionParameterResponse",
    "ActionMetadataResponse",
    "ReloadActionsResponse",
    # Runtime
    "BrowserSessionBaseParams",
    "BrowserSessionGetParams",
    "BrowserSessionCreateParams",
    "BrowserSessionAllRemoveParams",
    "BrowserSessionRemoveParams",
    "SessionCreateParams",
    "SessionCloseResponse",
    "SessionAllCloseResponse",
    "BrowserStatusEnum",
    "VideoStreamStatusEnum",
    "OperationPriority",
    "BrowserStatus",
    "LiveControlCommand",
    "VideoStreamParams",
    "VideoStreamStatus",
    "VideoStreamResponse",
    "HeartbeatRequest",
    "HeartbeatResponse",
    "ManualOperationRequest",
    "AutomationResumeRequest",
    "BrowserCleanupPolicy",
    "SessionLifecycleState",
    "BrowserSessionStatus",
    "CreateSessionRequest",
    "CreateSessionResponse",
    "BrowserIdParam",
    "VideoStreamStatusRequest",
    "VideoStreamMjpegRequest",
    "ScreenshotRequest",
    "BrowserStatusRequest",
    "NavigateRequest",
    "JavaScriptExecuteRequest",
    "BrowserClickRequest",
    "JavaScriptExecuteWithParamsRequest",
    "ForceReleaseRequest",
    "HeartbeatWithBrowserIdRequest",
    "CreateSessionWithBrowserIdRequest",
    "ManualOperationWithBrowserIdRequest",
    "AutomationResumeWithBrowserIdRequest",
    "BrowserCleanupPolicyRequest",
    "LiveControlCommandWithBrowserId",
    "StartVideoStreamRequest",
    "BrowserOperationRequest",
    "PausePluginsRequest",
    "ManualOperationResponse",
    "AutomationResumeResponse",
    "OperationStatusResponse",
    "PluginStatusResponse",
    "BrowserInfoResponse",
    "VideoStreamStatusResponse",
    "SystemStatisticsResponse",
    "CleanupPolicyResponse",
    "SystemCleanupResponse",
    "ForceReleaseResponse",
    "SystemHealthCheckResponse",
    "EmptyRequest",
    "BrowserInfoData",
    "VideoStreamStatusData",
    "ManualOperationResult",
    "AutomationResult",
    "OperationStatusData",
    "PluginStatusData",
    "SessionStatisticsData",
    "CreateSessionData",
    "BrowserSessionStatusData",
    "JavaScriptExecutionResult",
    "ModelInfo",
    "ChineseClickPredictionDetail",
    "WebRTCOfferResponse",
    "WebRTCAnswerRequest",
    "WebRTCAnswerResponse",
    "WebRTCIceCandidateRequest",
    "WebRTCIceCandidateResponse",
    "WebRTCGetIceCandidatesResponse",
    "WebRTCConnectionStatusResponse",
    "WebRTCCloseConnectionResponse",
    "RPAClickParams",
    "BrowserClickParams",
    "ClickResponse",
    "RPAFillParams",
    "RPAScrollParams",
    "RPAEvaluateParams",
    "RPAScreenshotParams",
    "RPAWaitParams",
    "RPANavigateParams",
    "JavaScriptExecuteParams",
    "ExecuteJsResponse",
    "SecurityCheckParams",
    "SecurityRisk",
    "SecurityCheckResult",
    "RPAResponse",
    "BrowserFingerprintCreateParams",
    "BrowserFingerprintUpdateParams",
    "BrowserFingerprintUpsertParams",
    "BrowserFingerprintQueryParams",
    "BrowserFingerprintDeleteParams",
    "BrowserFingerprintListParams",
    "BrowserFingerprintRenameParams",
    "BrowserFingerprintCreateResp",
    "BrowserFingerprintUpdateResp",
    "BrowserFingerprintDeleteResp",
    "BrowserFingerprintRenameResp",
    "BrowserFingerprintQueryResp",
    "BrowserOperationOpenUrlParams",
    "BrowserOperationScreenshotParams",
    "BrowserOperationReleaseParams",
    "BrowserOperationOpenUrlResp",
    "BrowserOperationScreenshotResp",
    "BrowserOperationReleaseResp",
    "SimplifiedHeartbeatRequest",
    "SimplifiedCreateSessionRequest",
    "SimplifiedManualOperationRequest",
    "SimplifiedAutomationResumeRequest",
    "SimplifiedLiveControlCommand",
    "SimplifiedStartVideoStreamRequest",
    "SimplifiedBrowserCleanupPolicyRequest",
    "SimplifiedScreenshotRequest",
    "SimplifiedNavigateRequest",
    "SimplifiedJavaScriptExecuteRequest",
    "SimplifiedBrowserClickRequest",
    "SimplifiedJavaScriptExecuteWithParamsRequest",
    "SimplifiedExecuteJSRequest",
    "SimplifiedVideoStreamMjpegRequest",
    "SimplifiedForceReleaseRequest",
    "SimplifiedPausePluginsRequest",
    # Live Service
    "BrowserSessionEntry",
    "VideoStreamInfo",
    "LiveStreamingEntry",
    "LiveServiceState",
    # Router
    "RouterPrefix",
    "BrowserFingerprintRouterPath",
    "BrowserSessionRouterPath",
    "BrowserControlRouterPath",
    "PluginRouterPath",
    "UserBrowserDefaultSettingRouterPath",
    "NotifyRouterPath",
    "RouterTag",
    "VersionTag",
    "RouterInfo",
    "DEFAULT_VERSION",
    "BROWSER_CONFIG_ROUTERS",
    "BROWSER_RUNTIME_ROUTERS",
    "SYSTEM_ROUTERS",
    "ALL_ROUTERS",
    "validate_router_uniqueness",
    # System
    "AdminSessionInfo",
    "AdminAllSessionsResponse",
    "AdminLiveStreamInfo",
    "AdminWebRTCConnectionInfo",
    "AdminAllStreamsResponse",
    "AdminAllStatsResponse",
    "PermissionLevelConfig",
    "PermissionConfigList",
    "PermissionConfigData",
    # Compatibility Aliases
    "UserBrowserInfoCreateParams",
    "UserBrowserInfoUpsertParams",
    "UserBrowserInfoCreateResp",
    "UserBrowserInfoCountParams",
    "UserBrowserInfoListParams",
    "UserBrowserInfoReadParams",
    "UserBrowserInfoReadResp",
    "UserBrowserInfoUpdateParams",
    "UserBrowserInfoUpdateResp",
    "UserBrowserInfoDeleteParams",
    "UserBrowserInfoDeleteResp",
    "BrowserOpenUrlParams",
    "BrowserOpenUrlResp",
    "BrowserScreenshotParams",
    "BrowserScreenshotResp",
    "BrowserReleaseParams",
    "BrowserReleaseResp",
    "StreamStatusResponse",
    "ExecuteJSResponse"
    ]
